my_ne_directory

diff --git a/0x00-shell_basics/6-firstdirectory b/0x00-shell_basics/6-firstdirectory
--- a/0x00-shell_basics/6-firstdirectory
+++ b/0x00-shell_basics/6-firstdirectory
@@ -1,2 +1,11 @@
 #!/bin/bash
-file temp/my_first_directory
+
+mkdir /tmp/my_first_directory
+
+if [ $? -eq 0 ]; then
+  echo "Directory created successfully"
+  file /tmp/my_first_directory/
+else
+  echo "Failed to create directory"
+fi
+
